model_name: MTR
# This .yaml is for a training configuration that lasts a small amount of epochs just to verify training is happening correctly

# Data Config
train_data_path: [/data2/dataset/waymo/scenario_processed/training] # CONSIDER CHANGING 
val_data_path: [/data2/dataset/waymo/scenario_processed/validation] # CONSIDER CHANGING 

# Model Config
encoder_layers: 4
decoder_layers: 4

# Training Params
seed: 42
batch_size: 128
num_workers: 8
lr: 0.0002
weight_decay: 0.01
epochs: 5
lr_warmup_step: 200
lr_step_freq: 200
lr_step_gamma: 0.96