model_name: MTR

# Data Config
train_data_path: [/data/dataset/CP-X-Prediction/Waymo/training_processed] # CONSIDER CHANGING 
val_data_path: [/data/dataset/CP-X-Prediction/Waymo/validation_processed] # CONSIDER CHANGING 

# Output Config
output_path: [/data/robert/CP-X-Prediction/MTR/output]

# Model Config
encoder_layers: 4
decoder_layers: 4

# Training Params
seed: 42
batch_size: 16 # originally 128
num_workers: 8
lr: 0.0002
weight_decay: 0.01
epochs: 50
lr_warmup_step: 200
lr_step_freq: 200
lr_step_gamma: 0.96
