model_name: MTR

# Data Config
train_data_path: [data_process_output/train_perception]
val_data_path: [data_process_output/test_gt]

# Model Config
encoder_layers: 4
decoder_layers: 4

# Training Params
seed: 42
batch_size: 128
num_workers: 8
lr: 0.0002
weight_decay: 0.01
epochs: 50
lr_warmup_step: 200
lr_step_freq: 200
lr_step_gamma: 0.96
