model_name: MTR
# Data Config
OBJECT_TYPE: &object_type ['TYPE_VEHICLE', 'TYPE_PEDESTRIAN', 'TYPE_CYCLIST']

DATA_ROOT: '/data/dataset/CP-X/data/waymo'
SPLIT_DIR: {
    'train': 'processed_scenarios_training', 
    'test': 'processed_scenarios_validation'
}

INFO_FILE: {
    'train': '/data/dataset/CP-X/data/waymo/processed_scenarios_training_infos.pkl', 
    'test': '/data/dataset/CP-X/data/waymo/processed_scenarios_val_infos.pkl'
}

SAMPLE_INTERVAL: {
    'train': 1, 
    'test': 1
}

WITHOUT_HDMAP: false

INFO_FILTER_DICT: 
    filter_info_by_object_type: *object_type

# for map feature encoding
POINT_SAMPLED_INTERVAL: 1
NUM_POINTS_EACH_POLYLINE: 20
VECTOR_BREAK_DIST_THRESH: 1.0

NUM_OF_SRC_POLYLINES: 768
CENTER_OFFSET_OF_MAP: &center_offset [30.0, 0]


# Data Config
train_data_path: [/data/dataset/CP-X/data/waymo/processed_scenarios_training] # CONSIDER CHANGING 
val_data_path: [/data/dataset/CP-X/data/waymo/processed_scenarios_validation] # CONSIDER CHANGING 

# Output Config
output_path: [/data/robert/CP-X-Prediction/MTR/output/train]

# Model Config
encoder_layers: 4 # used to be 4
decoder_layers: 4 # used to be 4

# Training Params
seed: 42
batch_size: 8 # used to be 10
num_workers: 8
lr: 0.00005 # from 0.0001
weight_decay: 0.01
epochs: 1
lr_warmup_step: 200
lr_step_freq: 200
lr_step_gamma: 0.96

# Logging file
log_file: '/data/robert/CP-X-Prediction/MTR/Prediction/logging/train_log_v2.txt'
